# Site settings
title: 小何的博客
email: zhiqihe@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  闫肃的博客
baseurl: "" # the subpath of your site, e.g. /blog/
#url: http://yansu.org  the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: hezhiqi

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
#twitter: suyan404
#weibo: suyan0830
github: hezhiqi
#instagram: suyan404
#linkedin: suyan404

# avatar and Favicon
avatar: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1575750022694&di=21b7259b4dc7450efbb1e0d182d8d235&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fforum%2Fpic%2Fitem%2F20a2c9ce3ca0187493457e50.jpg%3Fv%3Dtbs
favicon: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1575750022694&di=21b7259b4dc7450efbb1e0d182d8d235&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fforum%2Fpic%2Fitem%2F20a2c9ce3ca0187493457e50.jpg%3Fv%3Dtbs

# disqus config
#disqus:
#  shortname: suyan-zh

# google analytics config
#ga:
# id: UA-54767140-1
# url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

